[default]
description = "Default permissions for the RPC plugin"
permissions = [
    "allow-rpc-call",
    "allow-rpc-call-batch",
    "allow-rpc-procedures",
    "allow-rpc-subscribe",
    "allow-rpc-unsubscribe",
    "allow-rpc-subscription-count",
]
